version: '3.8'

services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=dynamodb
      - DEBUG=1
    networks:
      - app-network

  fastapi:
    build: ../../server
    container_name: fastapi-server
    ports:
      - "8000:8000"
    environment:
      - AWS_REGION=us-east-1
      - DYNAMO_TABLE=TrafficData
      - LOCALSTACK_URL=http://localstack:4566
    depends_on:
      - localstack
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
