services:
  fastapi-server:
    image: python:3.11-slim
    container_name: fastapi-server
    working_dir: /app
    volumes:
      - ../server:/app
    ports:
      - "8000:8000"
    command: >
      sh -c "pip install --no-cache-dir fastapi uvicorn &&
             uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
