services:
  fastapi-server:
    image: python:3.11-slim
    container_name: fastapi-server
    working_dir: /app
    volumes:
      - ../server:/app
    ports:
      - "8000:8000"
    command: >
      sh -c "pip install --no-cache-dir fastapi uvicorn boto3 &&
             uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    depends_on:
      - localstack

  localstack:
    image: localstack/localstack:2.1
    container_name: localstack
    environment:
      - SERVICES=dynamodb
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DEFAULT_REGION=us-east-1
    ports:
      - "4566:4566"
    volumes:
      - ./localstack_data:/tmp/localstack
